nome=input('Digite seu nome: ')
print('analisando seu nome...')
maiusculo= nome.upper()
print(f'Seu nome em letra maiuscula é: {maiusculo}')
minusculo= nome.lower()
print (f'Seu nome em letra minuscula é: {minusculo}')
sem_espaco= nome.replace(" ", "")
quantidade_de_letra= len(sem_espaco)
print(f'Seu nome tem {quantidade_de_letra} letras')
separa= nome.split()
print(separa)
achar= nome.find(" ")
print(f'seu primeiro nome tem {achar} letras')